# Generated by Django 4.1.3 on 2022-12-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_advert_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advert",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
