# Generated by Django 4.1.3 on 2022-12-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_advert_last_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("animal", models.CharField(max_length=100)),
                ("coordinates", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(default="")),
            ],
        ),
    ]
