# Generated by Django 4.1.3 on 2022-12-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_animalpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalpoint",
            name="coordinates",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
