# Generated by Django 4.1.3 on 2022-12-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_animalpoint_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalpoint",
            name="coordinates",
            field=models.JSONField(max_length=100),
        ),
    ]
